### ISSUE TITLE
MultipleItemPlayerLooper stop/resume looping

### ISSUE THREAD

**Issue by iosdeveloper** [quentinfasquel/TransparentVideoPlayer#1]
I can't figure out how to stop looping and resume it after. I found releasing the strong reference to the player looper stops looping, but creating a new player looper on the same player after would not loop the video.

https://github.com/quentinfasquel/TransparentVideoPlayer/blob/master/AlphaPlayerExample/GridViewController.swift#L68

Any help would be greatly appreciated. Thanks!

**Comment by quentinfasquel** [comment]
Hi @iosdeveloper, I'm sorry but I don't provide support for this project, it was really just a set of extensive tests attempting to synchronise playback & rendering of multiple videos at the same time, for which "transparent videos" is great application, however this isn't production ready.
